.\"     Title: FLUJCONF
.\"    Author: Kevin Brown <kev@flujos.org>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 10/05/2009
.\"    Manual: flujconf User Manual
.\"    Source: flujconf
.\"
.TH "FLUJCONF" "1" "10/05/2009" "flujconf" "flujconf User Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
flujconf \- configurator for darkice
.SH "SYNOPSIS"
.HP 9
\fBflujconf\fR \fB\-c\ \fR\fB\fI~/\&.darkice\&.cfg\fR\fR 
.HP 9
\fBflujconf\fR [{\fB\-help\fR} | {\fB\-v\fR}]
.SH "CONFIGURATOR FOR DARKICE"
.PP
This manual page documents briefly the
\fBflujconf\fR
command\&.
.PP
This manual page was written for the Debian distribution because the original program does not have a manual page\&. Instead, it has documentation in the GNU
\fBinfo\fR(1)
format; see below\&.
.PP
\fBflujconf\fR
is a program that\&.\&.\&.
.SH "OPTIONS"
.PP
The program follows the usual GNU command line syntax, with long options starting with two dashes (`\-\')\&. A summary of options is included below\&. For a complete description, see the
\fBinfo\fR(1)
files\&.
.PP
\fB\-c \fR\fB\fIdarkice.cfg\fR
.RS 4
Set flujconf defaults using a darkice.cfg\&.
.RE
.PP
\fB\-help\fR, \fB\-ayuda\fR
.RS 4
Show summary of options\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Show version of program\&.
.RE
.SH "FILES"
.PP
\fI${HOME}/\&.darkice\&.cfg\fR
.RS 4
The per\-user configuration file to control the behaviour of
flujconf\&. See
\fBfoo.conf\fR(5)
for further details\&.
.RE
.SH "BUGS"
.PP
a bunch of em\&.
.PP
.SH "AUTHOR"
.PP
\fBKevin Brown\fR <\&kev@flujos\&.org\&>
.sp -1n
.IP "" 4
Wrote this manpage for the Debian system\&.
.SH "COPYRIGHT"
Copyright \(co 2007 Kevin Brown
.br
.PP
This manual page was written for the Debian system (but may be used by others)\&.
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or (at your option) any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
\fI/usr/share/common\-licenses/GPL\fR\&.
.sp
